### ISSUE TITLE
'guestbookmessages.php' on line 262 missing ‘fopen’

### ISSUE THREAD

**Issue by freefire233** [jackmaessen/php-flafile-guestbook#1]
'guestbookmessages.php' file on line 262 use 'fclose' function, but before that, there was no corresponding 'fopen' function.--(My super poor English skills, ignore it. ^_^)

**Comment by jackmaessen** [comment]
Thanks very much for this notice. I will fix it!

**Comment by jackmaessen** [comment]
Issue fixed!

**Comment by jackmaessen** [comment]
issue fixed!
